# Production environment override
services:
  php:
    # Use pre-built production image from DockerHub (built by CI/CD)
    #    image: nicolascodemate/geoloc-map:latest

    # Optional: Uncomment to build locally instead of pulling from registry
    build:
      context: .
      target: frankenphp_prod

    env_file:
      - .env.prod.local
    volumes:
      - ./frankenphp/certs:/etc/caddy/certs:ro
    environment:
      SERVER_NAME: ${SERVER_NAME:-https://localhost}
      APP_ENV: prod
      CADDY_SERVER_EXTRA_DIRECTIVES: ${CADDY_SERVER_EXTRA_DIRECTIVES:-}

# Override volumes to use external volumes in production
# This ensures Let's Encrypt certificates persist across container recreations
volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
