name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  # or any branch you prefer

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker credentials for GCR
        run: echo "${{ secrets.GCP_SA_KEY }}" > keyfile.json

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth activate-service-account --key-file=keyfile.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/geoloc-map:latest .

      - name: Push Docker image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/geoloc-map:latest
